# Generated by Django 5.1.3 on 2024-12-03 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('appointment_duration', models.IntegerField(help_text='Duration in minutes')),
                ('monday_available', models.BooleanField(default=True, verbose_name='Monday Available')),
                ('tuesday_available', models.BooleanField(default=True, verbose_name='Tuesday Available')),
                ('wednesday_available', models.BooleanField(default=True, verbose_name='Wednesday Available')),
                ('thursday_available', models.BooleanField(default=True, verbose_name='Thursday Available')),
                ('friday_available', models.BooleanField(default=True, verbose_name='Friday Available')),
                ('saturday_available', models.BooleanField(default=False, verbose_name='Saturday Available')),
                ('sunday_available', models.BooleanField(default=False, verbose_name='Sunday Available')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='appointment.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Phone number must start with 5 and be 9 digits', regex='^5\\d{8}$')])),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.doctor')),
            ],
        ),
    ]
